version: "3.8"

services:
  redis:
  image: redis:latest
  container_name: hydrorich-redis
  ports:
    - "6379:6379"
  volumes:
    - redis_data:/data
  command: redis-server --appendonly yes
  networks:
    - hydrorich-network

volumes:
  redis_data:
  driver: local

networks:
  hydrorich-network:
    driver: bridge
